# Bienvenidos a la clase 5: AutoML

En esta notebook veremos en acci√≥n Pycaret una de las librerias de automl que nos permite probar varios modelos a la vez de manera muy rapida.  Primero instalemos las librerias mediante el uso de los siguientes dos comandos:

```
pip install pycaret
pip install mlflow
pip install gradio
```

In [16]:
import mlflow
from pycaret.classification import *
from pycaret.datasets import get_data

In [17]:
# cargamos el dataset
data = get_data('diabetes')

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [18]:
# Instanciamos la configuraci√≥n: setup
clf1 = setup(data, target = 'Class variable', log_experiment = True, experiment_name = 'diabetes1',use_gpu=True)

In [19]:
# model training
best_model = compare_models()

In [7]:
# inicializar server en consola !mlflow ui y luego ir a https://localhost:5000

Utilicemos una regresion logistica.

In [21]:
lr = create_model('lr')

In [8]:
# Creemos una app!!
create_app(lr)

Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.

(<gradio.routes.App at 0x1c53e027490>, 'http://127.0.0.1:7860/', None)

In [9]:
# cargamos otro dataset 
juice = get_data('juice')
exp_name = setup(data = juice,  target = 'Purchase',fix_imbalance=True, log_experiment = True, experiment_name = 'juice',use_gpu=True)

In [10]:
# entrenamos el modelo a model
dt = create_model('dt')

In [11]:
# creamos la api
create_api(dt, 'dt_api')

API sucessfully created. This function only creates a POST API, it doesn't run it automatically.

To run your API, please run this command --> !python dt_api.py

In [12]:
!python dt_api.py #You can see the server on localhost:8000/docs  https://www.youtube.com/watch?v=88M9c5Hc-k0

^C

In [15]:
evaluate_model(dt)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param‚Ä¶